version: '3.2'

services:
     php-fpm:
        build:
          context: .
          dockerfile: docker/php-fpm/Dockerfile
        container_name: stackext-php
        working_dir: /application
        volumes:
            - .:/application
        ports:
              - 1035:8000